---

# Defining for what BU's this program should run.
RUN_10080: TRUE
RUN_22880: FALSE
RUN_11711: FALSE

# Below Provide the values for all the respective BU for processing

VALUES_10080:
  HUB_SOURCE_LIST: "91G,91P,91D,91E,91I,91T"
  TRANSACTION_FILE_PATH : ""
  PLATFORM_PROC_DATE: ""
  MONTH: ""
  YEAR : ""
  CURRENCY : ""
  PLUG_FILE_PATH : ""
  MASTER_FILE_PATH : ""
  MASTER_FILE_PLUG_SHEETNAME : ""
  MASTER_FILE_GL_SHEETNAME : ""
  MASTER_FILE_RHA_SHEETNAME : ""
  RHA_FILE_PATH : ""
  RHA_WORK_OF_DATE : ""
  RHA_REPORTING_UNIT : ""
  RHA_MONTH_DETAIL : ""
  REVISED_VALUE_DATE : ""
  REVISED_WORK_OF_DATE : ""

VALUES_22880:
  HUB_SOURCE_LIST: "91G,91P,91D,91E,91I,91T"
  TRANSACTION_FILE_PATH : ""
  PLATFORM_PROC_DATE: ""
  MONTH: ""
  YEAR : ""
  CURRENCY : ""
  PLUG_FILE_PATH : ""
  MASTER_FILE_PATH : ""
  MASTER_FILE_PLUG_SHEETNAME : ""
  MASTER_FILE_GL_SHEETNAME : ""
  MASTER_FILE_RHA_SHEETNAME : ""
  RHA_FILE_PATH : ""
  RHA_WORK_OF_DATE : ""
  RHA_REPORTING_UNIT : ""
  RHA_MONTH_DETAIL : ""
  REVISED_VALUE_DATE : ""
  REVISED_WORK_OF_DATE : ""

VALUES_11711:
  HUB_SOURCE_LIST: "91G,91P,91D,91E,91I,91T"
  TRANSACTION_FILE_PATH : ""
  PLATFORM_PROC_DATE: ""
  MONTH: ""
  YEAR : ""
  CURRENCY : ""
  PLUG_FILE_PATH : ""
  MASTER_FILE_PATH : ""
  MASTER_FILE_PLUG_SHEETNAME : ""
  MASTER_FILE_GL_SHEETNAME : ""
  MASTER_FILE_RHA_SHEETNAME : ""
  RHA_FILE_PATH : ""
  RHA_WORK_OF_DATE : ""
  RHA_REPORTING_UNIT : ""
  RHA_MONTH_DETAIL : ""
  REVISED_VALUE_DATE : ""
  REVISED_WORK_OF_DATE : ""