LOAN_DATA_FILE_PATH: "Loan Data - Original.xlsx"

LOAN_DETAILS1_SHEET_NAME: "Loan Details-1"
LOAN_DETAILS2_SHEET_NAME: "Loan Details-2"
FX_RATES_SHEET_NAME: "FX Rates"

PAYMENT_FREQUENCY_MONTHLY: 30
PAYMENT_FREQUENCY_QUATERLY: 91
PAYMENT_FREQUENCY_HALF_YEARLY: 182
PAYMENT_FREQUENCY_YEARLY: 365

OUTPUT_FILE_PATH: "Loan_Output.xlsx"